version: '3.4'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=ecoflow
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"